### ISSUE TITLE
Rationalise charts

### ISSUE THREAD

**Issue by nickynicolson** [OA-WCVP/paper#27]
- [ ] Open access status - OA T/F and the kinds of OA used (closed, green, gold etc) - issue #24 
- [ ] Journal breakdown - indicating OA use at journal level - issue #25 
- [ ] Map - indicating OA T/F by country - issue #26
